/**
 * lib/mock-data.ts
 *
 * All fake data used throughout the app during development.
 * In production, this data comes from Supabase (PostgreSQL database).
 * Having this in one place makes it easy to swap out for real API calls later.
 */

import type {
  Creator,
  Booking,
  QueueEntry,
  ChatMessage,
  CreatorStats,
  CallPackage,
} from "@/types";

// ── Creators / Influencers ────────────────────────────────────────────
export const MOCK_CREATORS: Creator[] = [
  {
    id: "1",
    name: "Luna Vasquez",
    username: "@lunavfit",
    bio: "Certified personal trainer & nutrition coach with 6 years experience. DMs are overwhelming — book a call and let's actually talk about YOUR goals.",
    category: "Fitness & Wellness",
    tags: ["Fitness", "Nutrition", "Mindset"],
    followers: "48.2K",
    rating: 4.9,
    reviewCount: 214,
    avatarInitials: "LV",
    avatarColor: "bg-violet-600",
    isLive: true,
    queueCount: 4,
    callPrice: 25,
    callDuration: 15,
    nextAvailable: "Live Now",
    totalCalls: 892,
    responseTime: "~2 min",
  },
  {
    id: "2",
    name: "Marcus Jin",
    username: "@marcusjin",
    bio: "Growth hacker & startup founder. Built 3 companies from $0 to $1M+. Ask me anything about product, fundraising, or going viral.",
    category: "Business & Startups",
    tags: ["Startups", "Growth", "Marketing"],
    followers: "92.1K",
    rating: 4.8,
    reviewCount: 378,
    avatarInitials: "MJ",
    avatarColor: "bg-blue-600",
    isLive: false,
    queueCount: 0,
    callPrice: 50,
    callDuration: 20,
    nextAvailable: "Today, 4:30 PM",
    totalCalls: 1240,
    responseTime: "~5 min",
  },
  {
    id: "3",
    name: "Aisha Okonkwo",
    username: "@aishacreates",
    bio: "Full-time content creator & UGC coach. I've worked with 40+ brands. Let me review your portfolio or pitch strategy.",
    category: "Content Creation",
    tags: ["UGC", "Brand Deals", "Editing"],
    followers: "31.7K",
    rating: 5.0,
    reviewCount: 89,
    avatarInitials: "AO",
    avatarColor: "bg-pink-600",
    isLive: true,
    queueCount: 2,
    callPrice: 20,
    callDuration: 15,
    nextAvailable: "Live Now",
    totalCalls: 413,
    responseTime: "~1 min",
  },
  {
    id: "4",
    name: "Theo Nakamura",
    username: "@theonakamura",
    bio: "Day trader & options educator. Teaching retail investors to think like institutions — no hype, just data.",
    category: "Finance & Investing",
    tags: ["Trading", "Stocks", "Options"],
    followers: "67.4K",
    rating: 4.7,
    reviewCount: 156,
    avatarInitials: "TN",
    avatarColor: "bg-emerald-600",
    isLive: false,
    queueCount: 0,
    callPrice: 40,
    callDuration: 20,
    nextAvailable: "Tomorrow, 10:00 AM",
    totalCalls: 654,
    responseTime: "~10 min",
  },
  {
    id: "5",
    name: "Sofia Reyes",
    username: "@sofiareyes",
    bio: "Skincare obsessed. Board-certified esthetician. I'll review your entire routine and give you a real roadmap — not just a product list.",
    category: "Beauty & Skincare",
    tags: ["Skincare", "Beauty", "Wellness"],
    followers: "112K",
    rating: 4.9,
    reviewCount: 502,
    avatarInitials: "SR",
    avatarColor: "bg-rose-600",
    isLive: false,
    queueCount: 0,
    callPrice: 30,
    callDuration: 15,
    nextAvailable: "Today, 7:00 PM",
    totalCalls: 1876,
    responseTime: "~3 min",
  },
  {
    id: "6",
    name: "Devon Clarke",
    username: "@devonclarke",
    bio: "Senior SWE @ Big Tech. Let me review your resume, prep you for behavioral rounds, or do a mock coding interview. Real feedback only.",
    category: "Tech & Career",
    tags: ["SWE", "Interview Prep", "Career"],
    followers: "44.8K",
    rating: 4.8,
    reviewCount: 201,
    avatarInitials: "DC",
    avatarColor: "bg-sky-600",
    isLive: false,
    queueCount: 0,
    callPrice: 45,
    callDuration: 30,
    nextAvailable: "Today, 6:00 PM",
    totalCalls: 743,
    responseTime: "~7 min",
  },
];

// ── Bookings (Creator Dashboard view) ─────────────────────────────────
export const MOCK_BOOKINGS: Booking[] = [
  {
    id: "b1",
    creatorId: "1",
    creatorName: "Luna Vasquez",
    fanName: "Jordan Kim",
    fanUsername: "@jordankim",
    date: "2025-08-05",
    time: "3:00 PM",
    duration: 15,
    price: 25,
    status: "upcoming",
    topic: "Weight loss plateau — need a new program",
  },
  {
    id: "b2",
    creatorId: "1",
    creatorName: "Luna Vasquez",
    fanName: "Riley Chen",
    fanUsername: "@rileyc",
    date: "2025-08-05",
    time: "3:30 PM",
    duration: 15,
    price: 25,
    status: "upcoming",
    topic: "Marathon training nutrition plan",
  },
  {
    id: "b3",
    creatorId: "1",
    creatorName: "Luna Vasquez",
    fanName: "Priya Sharma",
    fanUsername: "@priyasfit",
    date: "2025-08-04",
    time: "2:00 PM",
    duration: 15,
    price: 25,
    status: "completed",
    topic: "Home workout routine for beginners",
    rating: 5,
  },
  {
    id: "b4",
    creatorId: "1",
    creatorName: "Luna Vasquez",
    fanName: "Alex Torres",
    fanUsername: "@alextfit",
    date: "2025-08-04",
    time: "4:00 PM",
    duration: 15,
    price: 25,
    status: "completed",
    topic: "Cutting diet while maintaining muscle",
    rating: 5,
  },
  {
    id: "b5",
    creatorId: "1",
    creatorName: "Luna Vasquez",
    fanName: "Sam Nguyen",
    fanUsername: "@samn",
    date: "2025-08-03",
    time: "1:00 PM",
    duration: 15,
    price: 25,
    status: "completed",
    topic: "Post-injury comeback training",
    rating: 4,
  },
];

// ── Queue entries (Live session waiting room) ──────────────────────────
export const MOCK_QUEUE: QueueEntry[] = [
  {
    id: "q1",
    fanName: "Jordan Kim",
    fanUsername: "@jordankim",
    avatarInitials: "JK",
    avatarColor: "bg-violet-500",
    position: 1,
    waitTime: "~2 min",
    topic: "Weight loss plateau",
    joinedAt: new Date(Date.now() - 3 * 60000).toISOString(),
  },
  {
    id: "q2",
    fanName: "Riley Chen",
    fanUsername: "@rileyc",
    avatarInitials: "RC",
    avatarColor: "bg-sky-500",
    position: 2,
    waitTime: "~17 min",
    topic: "Marathon nutrition",
    joinedAt: new Date(Date.now() - 1 * 60000).toISOString(),
  },
  {
    id: "q3",
    fanName: "Priya Sharma",
    fanUsername: "@priyasfit",
    avatarInitials: "PS",
    avatarColor: "bg-pink-500",
    position: 3,
    waitTime: "~32 min",
    topic: "Beginner home workouts",
    joinedAt: new Date(Date.now() - 30000).toISOString(),
  },
  {
    id: "q4",
    fanName: "Alex Torres",
    fanUsername: "@alextfit",
    avatarInitials: "AT",
    avatarColor: "bg-emerald-500",
    position: 4,
    waitTime: "~47 min",
    topic: "Cutting while maintaining muscle",
    joinedAt: new Date(Date.now() - 10000).toISOString(),
  },
];

// ── Chat messages (Waiting room chat) ─────────────────────────────────
export const MOCK_CHAT: ChatMessage[] = [
  {
    id: "c1",
    username: "@lunavfit",
    avatarInitials: "LV",
    avatarColor: "bg-violet-600",
    message: "Hey everyone! Give me 5 min to wrap up this call, then I'll start admitting the queue 🔥",
    timestamp: new Date(Date.now() - 8 * 60000).toISOString(),
    isCreator: true,
  },
  {
    id: "c2",
    username: "@jordankim",
    avatarInitials: "JK",
    avatarColor: "bg-violet-500",
    message: "Can't wait! Been watching your reels for months, this is exciting",
    timestamp: new Date(Date.now() - 7 * 60000).toISOString(),
  },
  {
    id: "c3",
    username: "@rileyc",
    avatarInitials: "RC",
    avatarColor: "bg-sky-500",
    message: "Same!! @jordankim same, we love Luna 😭",
    timestamp: new Date(Date.now() - 6 * 60000).toISOString(),
  },
  {
    id: "c4",
    username: "@priyasfit",
    avatarInitials: "PS",
    avatarColor: "bg-pink-500",
    message: "Quick question while we wait — does she do program reviews or just calls?",
    timestamp: new Date(Date.now() - 4 * 60000).toISOString(),
  },
  {
    id: "c5",
    username: "@lunavfit",
    avatarInitials: "LV",
    avatarColor: "bg-violet-600",
    message: "@priyasfit I do both! We can review your current program live on the call 💪",
    timestamp: new Date(Date.now() - 3 * 60000).toISOString(),
    isCreator: true,
  },
];

// ── Creator Dashboard Stats ────────────────────────────────────────────
export const MOCK_CREATOR_STATS: CreatorStats = {
  totalEarnings: 4280,
  callsThisMonth: 47,
  avgRating: 4.9,
  upcomingBookings: 8,
  totalFans: 892,
  conversionRate: 12.4,
};

// ── Call Packages (Creator's offering menu) ────────────────────────────
export const MOCK_CALL_PACKAGES: CallPackage[] = [
  {
    id: "p1",
    name: "Quick Chat",
    duration: 15,
    price: 25,
    description: "Great for quick questions, form checks, or a simple progress review.",
    isActive: true,
    bookingsCount: 412,
  },
  {
    id: "p2",
    name: "Deep Dive",
    duration: 30,
    price: 45,
    description: "Full program build, nutrition audit, or detailed strategy session.",
    isActive: true,
    bookingsCount: 187,
  },
  {
    id: "p3",
    name: "VIP Hour",
    duration: 60,
    price: 80,
    description: "Everything in Deep Dive + a written follow-up plan sent after the call.",
    isActive: false,
    bookingsCount: 23,
  },
];
