ALTER TABLE public.bookings
ADD COLUMN IF NOT EXISTS creator_present BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS fan_present BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS creator_joined_at TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS fan_joined_at TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS auto_cancelled_at TIMESTAMPTZ;
